name: Build and Publish to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main


    
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: my-next-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Run the build using npm
        - run: npm ci && npm run build

        - name: Login to ECR
        - id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build Docker image
          run: docker build -t ${{ env.ECR_REPOSITORY }}:latest .
          
        - name: Push Docker image to ECR
          run: docker push ${{ env.ECR_REPOSITORY }}:latest    

